name: Release Workflow

on:
  push:
    tags:
      - 'v*' # Se dispara solo al subir un tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generar artefacto (.jar)
        run: ./mvnw clean package

      - name: Construir Imagen Docker
        run: docker build -t mgcss-track-l2group5:${{ github.ref_name }} .

      - name: Publicar Release en GitHub y adjuntar artefacto
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          files: target/*.jar
          generate_release_notes: true